---
ParameterGroup:
  name: Application
  parameters:
  - { name: OverrideBaseColor, type: float, value: 0.2 }
  - { name: OverrideShading, type: float, value: 0.5 }
  - { name: UserMetalness, type: float, value: 0.2 }
  - { name: UserRoughness, type: float, value: 0.7 }
  - { name: Time, type: float, value: 0.0 }

---
ParameterGroup:
  name: Camera
  parameters:
  - { name: View, type: mat4 }
  - { name: IView, type: mat4 }
  - { name: Projection, type: mat4 }
  - { name: IProjection, type: mat4 }
  - { name: ViewOld, type: mat4 }
  - { name: Parameters, type: vec4 }
  - { name: PositionWS, type: vec3 }

---
ParameterGroup:
  name: SSAO
  parameters:
  - { name: NumSamples, type: int, value: 32 }
  - { name: Radius, type: float, value: 10.0 }
  - { name: Intensity, type: float, value: 1.5 }
  - { name: Samples, type: vec4, elements: 32 }
  textures:
  - { name: Noise }

---
ParameterGroup:
  name: SSR
  parameters:
  - { name: CoarseStep, type: float, value: 0.5 }
  - { name: NumCoarseSteps, type: int, value: 100 }
  - { name: NumPrecisionSteps, type: int, value: 8 }
  - { name: FacingThreshold, type: float, value: 0.5 }
  - { name: DepthBypassThreshold, type: float, value: 0.5 }
  - { name: BRDFBias, type: float, value: 0.7 }
  - { name: MinStepMultiplier, type: float, value: 0.25 }
  - { name: MaxStepMultiplier, type: float, value: 4.0 }
  textures:
  - { name: Noise, path: assets/textures/blue_noise.png }

---
RenderBuffers:
- { name: GBufferBaseColor, format: R8G8B8A8_UNORM }
- { name: GBufferShading, format: R8G8_UNORM }
- { name: GBufferNormal, format: R16G16B16A16_SFLOAT }
- { name: GBufferDepth, format: D32_SFLOAT }
- { name: GBufferVelocity, format: R16G16_SFLOAT }

---
RenderBuffers:
- { name: SSAORough, format: R8G8B8A8_UNORM }
- { name: SSAO, format: R8G8B8A8_UNORM }

---
RenderBuffers:
- { name: LBufferDiffuse, format: R16G16B16A16_SFLOAT }
- { name: LBufferSpecular, format: R16G16B16A16_SFLOAT }

---
RenderBuffers:
- { name: SSRTrace, format: R16G16B16A16_SFLOAT }
- { name: SSR, format: R16G16B16A16_SFLOAT }
- { name: SSRVelocity, format: R16G16_SFLOAT }
- { name: SSRTAA, format: R16G16B16A16_SFLOAT }
- { name: SSROld, format: R16G16B16A16_SFLOAT }

---
RenderBuffers:
- { name: Composite, format: R16G16B16A16_SFLOAT }
- { name: CompositeTAA, format: R16G16B16A16_SFLOAT }
- { name: CompositeOld, format: R16G16B16A16_SFLOAT }

---
RenderBuffers:
- { name: Color, format: R8G8B8A8_UNORM }

---
RenderPass:
  name: Prepare
  type: RenderPassPrepareOld
  output_colors:
  - { name: CompositeOld, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  - { name: SSROld, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  vertex_shader: assets/shaders/common/Default.vert

---
RenderPass:
  name: GBuffer
  type: RenderPassGeometry
  input_groups: [ Application, Camera ]
  input_material_binding: 2
  output_colors:
  - { name: GBufferBaseColor, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  - { name: GBufferNormal, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  - { name: GBufferShading, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  - { name: GBufferVelocity, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  output_depthstencil: { name: GBufferDepth, load_op: CLEAR, clear_depthstencil: "1.0, 0" }
  vertex_shader: assets/shaders/render_graph/passes/gbuffer/GBuffer.vert
  fragment_shader: assets/shaders/render_graph/passes/gbuffer/GBuffer.frag

---
RenderPass:
  name: SSAO
  type: RenderPassPost
  input_groups: [ Camera, SSAO ]
  input_renderbuffers: [ GBufferNormal, GBufferDepth ]
  output_colors:
  - { name: SSAORough, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/ssao/SSAO.frag

---
RenderPass:
  name: SSAO Blur
  type: RenderPassPost
  input_renderbuffers: [ SSAORough ]
  output_colors:
  - { name: SSAO, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/ssao_blur/SSAOBlur.frag

---
RenderPass:
  name: LBuffer Skylight
  type: RenderPassLBuffer
  input_groups: [ Camera ]
  input_renderbuffers: [ GBufferBaseColor, GBufferNormal, GBufferShading, GBufferDepth ]
  input_light_binding: 5
  output_colors:
  - { name: LBufferDiffuse, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  - { name: LBufferSpecular, load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/lbuffer/LBufferSkylight.frag

---
RenderPass:
  name: SSR Trace
  type: RenderPassPost
  input_groups: [ Application, Camera, SSR ]
  input_renderbuffers: [ GBufferNormal, GBufferShading, GBufferDepth ]
  output_colors:
  - { name: SSRTrace, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/ssr_trace/SSRTrace.frag

---
RenderPass:
  name: SSR Resolve
  type: RenderPassPost
  input_groups: [ Application, Camera, SSR ]
  input_renderbuffers: [ GBufferBaseColor, GBufferNormal, GBufferShading, GBufferDepth, SSRTrace, CompositeOld ]
  output_colors:
  - { name: SSR, load_op: DONT_CARE }
  - { name: SSRVelocity, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/ssr_resolve/SSRResolve.frag

---
RenderPass:
  name: SSR Temporal Filter
  type: RenderPassPost
  input_renderbuffers: [ SSR, SSRVelocity, SSROld ]
  output_colors:
  - { name: SSRTAA, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/temporal_filter/TemporalFilter.frag

---
RenderPass:
  name: Composite
  type: RenderPassPost
  input_renderbuffers: [ LBufferDiffuse, LBufferSpecular, SSAO, SSRTAA ]
  output_colors:
  - { name: Composite, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/composite/Composite.frag

---
RenderPass:
  name: AA Temporal Filter
  type: RenderPassPost
  input_renderbuffers: [ Composite, GBufferVelocity, CompositeOld ]
  output_colors:
  - { name: CompositeTAA, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/temporal_filter/TemporalFilter.frag

---
RenderPass:
  name: Tonemap
  type: RenderPassPost
  input_renderbuffers: [ CompositeTAA ]
  output_colors:
  - { name: Color, load_op: DONT_CARE }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/tonemap/Tonemap.frag

---
RenderPass:
  name: Gamma
  type: RenderPassPost
  input_renderbuffers: [ Color ]
  output_swapchain: { load_op: CLEAR, clear_color: "0.0, 0.0, 0.0, 0.0" }
  vertex_shader: assets/shaders/common/Default.vert
  fragment_shader: assets/shaders/render_graph/passes/gamma/Gamma.frag

---
RenderPass:
  name: ImGui
  type: RenderPassImGui
  output_swapchain: { load_op: LOAD }
  vertex_shader: assets/shaders/render_graph/passes/imgui/ImGui.vert
  fragment_shader: assets/shaders/render_graph/passes/imgui/ImGui.frag

---
RenderPass:
  name: Swap
  type: RenderPassSwapRenderBuffers
  pairs:
  - { src: CompositeTAA, dst: CompositeOld }
  - { src: SSRTAA, dst: SSROld }
